### ISSUE TITLE
Add tooltips for icons

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#442] opened 2017-09-14 17:57 UTC
@shepmaster suggested tooltips for the various buttons, and I think it's a great idea! 
<img width="55" alt="buttons" src="https://user-images.githubusercontent.com/27786/30445643-a5e9f774-9954-11e7-9c85-57de0c83994a.png">
 isn't very obvious

**Comment by azerupi** [comment] 2017-09-14 18:28
Closing as a duplicate of #388 :)

**Closed by azerupi** 2017-09-14 18:28 UTC

**Comment by steveklabnik** [comment] 2017-09-14 19:58
Gah! sorry about that!
