### ISSUE TITLE
Some markdown syntax missing build process

### ISSUE THREAD

**Issue by MertcanGokgoz** [azerupi/mdBook#169] opened 2016-09-01 06:11 UTC
Hi

some markdown syntax missing build process

![bold](https://cloud.githubusercontent.com/assets/8042604/18157050/9ef183ca-7023-11e6-919f-236db87ba47f.png)
![image](https://cloud.githubusercontent.com/assets/8042604/18157051/9ef4af96-7023-11e6-9948-3eba9b8564af.png)

**Comment by azerupi** [comment] 2016-09-01 12:07
Could you give me some more background? Something I can use to reproduce this bug? Thanks!

**Comment by MertcanGokgoz** [comment] 2016-09-01 14:14
im use custom html tag and bind markdown

example:

```
<p align="center">
![javascriptgorsel](http://www.javatpoint.com/images/javascript/javascript_logo.png)
</p>
```

and

```
<center>
- **Float** : Bizdeki virgüllü sayıları
- **Integer** : Sayıları oluşturan ve
- **String** : Metinsel ifadelerdir. "Merhaba" "
- **Boolean** : Doğru yada Yanlış olabilir.
- **Arrays** : Birden çok değişkeni tanımlarken kullanılır.
- **Null** : Değeri olmayan ifadelerde kullanılır.
- **undefined** : adında
</center>
```

**Comment by azerupi** [comment] 2017-05-16 12:30
Sorry it took so long to respond. :confused: 
So I checked the [CommonMark spec](http://spec.commonmark.org/0.27/#html-blocks) which is what pulldown-cmark uses, and it states that HTML blocks do not interpret markdown inside of them. Everything inside raw HTML blocks will be copied over literally.

So even if it is inconvenient, it is actually not a bug. So I am closing this issue if it's ok with you. :blush:

**Closed by azerupi** 2017-05-16 12:30 UTC
