### ISSUE TITLE
Add CSS without overriding theme

### ISSUE THREAD

**Issue by rap2hpoutre** [azerupi/mdBook#266] opened 2017-05-05 13:21 UTC
Maybe I misunderstood something but it seems the CSS theme must be fully replaced if I want to add a rule. So if I did understand well, if I just want to add a simple rule (ex: `h1 { color: #f00; }`) I must copy the original file then add my rule at the end of the file. 

If so, maybe we should add the possibility to create an optional `custom.css` where we could add our simple rules over the existing ones? I could submit a PR if you want.

**Comment by steveklabnik** [comment] 2017-05-05 14:01
You are right, but this is almost an exact duplicate of https://github.com/azerupi/mdBook/issues/178, down to the file name! 😄 So thanks, but closing as a duplicate.

**Closed by steveklabnik** 2017-05-05 14:01 UTC

**Comment by rap2hpoutre** [comment] 2017-05-05 14:10
Oops.
